django_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('tracker/', include('study_tracker.urls')),
]

main/urls.py
from django.urls import path

from main.views import *

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
]

study_tracker/urls.py
from django.urls import path
from study_tracker.views import show_tracker
from study_tracker.views import add_assignment
from study_tracker.views import show_xml
from study_tracker.views import show_json
from study_tracker.views import register
from study_tracker.views import login_user
from study_tracker.views import logout_user
from study_tracker.views import modify_assignment
from study_tracker.views import delete_assignment
from study_tracker.views import add_assignment_ajax

app_name = 'study_tracker'

urlpatterns = [
    path('', show_tracker, name='show_tracker'),
    path('add_assignment/', add_assignment, name='add_assignment'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('modify/<int:id>', modify_assignment, name='modify_assignment'),
    path('delete/<int:id>', delete_assignment, name='delete_assignment'),
    path('create-ajax/', add_assignment_ajax, name='add_assignment_ajax'),
    ]

study_tracker/models.py
from django.db import models

# Create your models here.
class Assignment    (models.Model):
    name = models.CharField(max_length=50)
    subject = models.CharField(max_length=20)
    progress = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()

study_tracker/forms.py
from django.forms import ModelForm
from study_tracker.models import Assignment

class AssignmentForm(ModelForm):
    class Meta:
        model = Assignment
        fields = ['name', 'subject', 'progress', 'description']

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

study_tracker/views.py
from django.shortcuts import render
from study_tracker.models import Assignment
from django.http import HttpResponseRedirect
from study_tracker.forms import AssignmentForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='study_tracker:login')
def show_tracker(request):
    assignments = Assignment.objects.all()
    context = {
        'list_of_assignments': assignments,
        'name': request.user.username,
        'last_login': request.COOKIES.get('last_login'),
        'total': Assignment.objects.filter(progress__lt=100).count(),
    }
    return render(request, 'tracker.html', context)

def add_assignment(request):
    if request.method == 'POST':
        form = AssignmentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('study_tracker:show_tracker'))
    else:
        form = AssignmentForm()
    context = {
        'form': form
    }
    return render(request, 'add_assignment.html', context)

def show_xml(request):
    assignments = Assignment.objects.all()
    xml = serializers.serialize('xml', assignments)
    return HttpResponse(xml, content_type='text/xml')

def show_json(request):
    assignments = Assignment.objects.all()
    json = serializers.serialize('json', assignments)
    return HttpResponse(json, content_type='application/json')

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('study_tracker:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("study_tracker:show_tracker")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response       
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('study_tracker:login'))
    response.delete_cookie('last_login')
    return redirect('study_tracker:login')

def modify_assignment(request, id):
    # Get data berdasarkan ID
    assignment = Assignment.objects.get(pk = id)

    # Set instance pada form dengan data dari assignment
    form = AssignmentForm(request.POST or None, instance=assignment)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('study_tracker:show_tracker'))

    context = {'form': form}
    return render(request, "modify_assignment.html", context)

def delete_assignment(request, id):
    # Get data berdasarkan ID
    assignment = Assignment.objects.get(pk = id)
    # Hapus data
    assignment.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('study_tracker:show_tracker'))

@csrf_exempt
def add_assignment_ajax(request):
    form = AssignmentForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        form.save()
        data = Assignment.objects.last()

        result = {
            'id': data.id,
            'name': data.name,
            'subject': data.subject,
            'progress': data.progress,
            'date': data.date,
            'description': data.description,
        }
        return JsonResponse(result)
    
    context = {'form': form}
    return render(request, "add_assignment.html", context)

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  {% block content %}
  {% endblock content %}
</body>

<style>
  body {
    background-color: bisque;
    background-size: cover;
    background-repeat: no-repeat;
    background-attachment: fixed;
  }
</style>

</html>

study_tracker/templates/add_assignment.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<title>Tambah Assignment Baru</title>

<h1>Tambah Assignment Baru</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Tambah"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

study_tracker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Study Tracker</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>  
  {% block content %}
  {% endblock content %}
</body>

</html>

study_tracker/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <p><img src="{% static 'img/django-logo-negative.svg' %}"></p>
{% endblock content %}

study_tracker/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1 class="text-center">Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>

            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Belum mempunyai akun? <a href="{% url 'study_tracker:register' %}">Buat Akun</a>

</div>

<style>
    .login {
        width: 300px;
        margin-top: -150px;
        margin-left: -150px;
        position: absolute;
        top: 50%;
        left: 50%;
        padding: 20px;
        border: 1px solid #000000;
        border-radius: 5px;
        background-color: #ffffff;
        opacity: 0.9;
    }
</style>

{% endblock content %}

study_tracker/templates/modify_assignment.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<title>Ubah Data Tugas</title>

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{request.user.username}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'study_tracker:logout' %}">Log Out</a>
          </li>
        </ul>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal">
          Tambah Assignment
        </button>
      </div>
    </div>
  </nav>  

<div class="modify">
    <h1>Ubah Data Tugas</h1>
    <form method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Ubah"/>
                </td>
            </tr>
        </table>
    </form>
</div>

<style>
    .modify {
        width: 700px;
        margin-top: -225px;
        margin-left: -350px;
        position: absolute;
        top: 50%;
        left: 50%;
        padding: 20px;
        border: 1px solid #000000;
        border-radius: 5px;
        background-color: #ffffff;
        opacity: 0.9;
    }
</style>

{% endblock %}

study_tracker/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">

    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

<style>
    .login {
        width: 700px;
        margin-top: -225px;
        margin-left: -350px;
        position: absolute;
        top: 50%;
        left: 50%;
        padding: 20px;
        border: 1px solid #000000;
        border-radius: 5px;
        background-color: #ffffff;
        opacity: 0.9;
    }
</style>

{% endblock content %}

study_tracker/templates/tracker.html
{% extends 'base.html' %}

{% block content %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<title>Study Tracker</title>

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{request.user.username}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'study_tracker:logout' %}">Log Out</a>
          </li>
        </ul>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createModal">
          Tambah Assignment
        </button>
      </div>
    </div>
  </nav>  

<script>
    $(document).ready(function(){
        $.get("/tracker/json/", function(data) {
            for (i=0; i<data.length; i++){
                $('#tracker').append(`
                <div id="${data[i].id}--task" class="col-md-6 col-lg-3 mb-3">
                    <div class="card d-flex">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">${data[i].fields.name}</h5>
                            <p class="card-text date">${data[i].fields.date}</p>
                            <p class="card-text">${data[i].fields.subject}</p>
                            <p class="card-text">${data[i].fields.progress}</p>
                            <p class="card-text">${data[i].fields.description}</p>
                            <div class="mt-auto">
                                <a href="/tracker/delete/${data[i].pk}" class="btn btn-primary delete mb-2">Hapus</a>
                                <a href="/tracker/modify/${data[i].pk}" class="btn btn-secondary mb-2">Ubah</a>
                            </div>
                        </div>
                    </div>
                </div>
                `)
            }
        });
  
        $("#submit_btn").click(function(){
            $.post("/tracker/create-ajax/", {
                name: $("#name").val(),
                subject: $("#subject").val(),
                progress: $("#progress").val(),
                description: $("#description").val()
            },
            function(result, status){
                if (status == 'success'){
                    $("#tracker").append(`
                    <div id="${result.id}--task" class="col-md-6 col-lg-3 mb-3">
                        <div class="card d-flex">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">${result.name}</h5>
                                <p class="card-text date">${result.date}</p>
                                <p class="card-text">${result.subject}</p>
                                <p class="card-text">${result.progress}</p>
                                <p class="card-text">${result.description}</p>
                                <div class="mt-auto">
                                    <a href="/tracker/delete/${result.id}" class="btn btn-primary delete mb-2">Hapus</a>
                                    <a href="/tracker/modify/${result.id}" class="btn btn-secondary mb-2">Ubah</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    `);
                $('#name').val('')
                $('#date').val('')
                $('#progress').val('')
                $('#description').val('')
                }
            })
        })
    })
  </script>
  
    <body>
      <h4 class="text-center">Hai {{name}}, kamu memiliki {{total}} tugas yang harus dikerjakan!</h4>
      <h3 class="text-center">Data Assignment</h3>
  
      <!-- Modal -->
      <div class="modal" id="createModal" tabindex="-1" aria-labelledby="createModalLabel" aria-hidden="true">
          <div class="modal-dialog">
          <div class="modal-content">
              <div class="modal-header">
              <h1 class="modal-title fs-5" id="createModalLabel">Tambah Assignment</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
              </div>
              <div class="modal-body">
              {% csrf_token %}
              <label for="name" class="form-label">Judul Assignment:</label><br>
              <input type="text" id="name" class="form-control" name="name" placeholder="Tutorial"><br>
              <label for="subject" class="form-label">Nama Matkul:</label>
              <input type="text" id="subject" class="form-control" name="subject" placeholder="PBP"><br>
              <label for="progress" class="form-label">Progress:</label><br>
              <input type="number" id="progress" class="form-control" name="progress" placeholder="0 - 100"><br>
              <label for="description" class="form-label">Deskripsi Tugas:</label><br>
              <input type="text" id="description" class="form-control" name="description" placeholder="Tugas untuk Bulan Mei"><br>
              </div>
              <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
              <button id="submit_btn" type="button" class="btn btn-primary create" id="add-task" data-bs-dismiss="modal">Add</button>
              </div>
          </div>
          </div>
      </div>
  </body>

<div class="row m-2" id="tracker"></div>

<h7>Sesi terakhir login: {{ last_login }}</h7>

<style>
  .container {
    border-color: rgb(255, 255, 255);
  }
</style>
  
{% endblock content %}